version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    assignees:
      - gavlyukovskiy
    groups:
      go-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - gavlyukovskiy
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
