self: permissionizer/server
allow:
  - repository: permissionizer/request-token
    permissions:
      contents: read
      issues: write
    groups:
      go-minor:
        update-types:
          - minor
          - patch
