package types

import (
	"time"

	"github.com/google/go-github/v71/github"
)

type IssueTokenRequest struct {
	TargetRepositories []string          `json:"target_repositories"`
	Permissions        map[string]string `json:"permissions"`
}

type IssueTokenResponse struct {
	Token        string                          `json:"token"`
	ExpiresAt    *time.Time                      `json:"expires_at"`
	Permissions  *github.InstallationPermissions `json:"permissions"`
	Repositories []string                        `json:"repositories"`
	IssuedBy     *TokenRequestor                 `json:"issued_by"`
}

type TokenRequestor struct {
	Repository  string `json:"repository"`
	Ref         string `json:"ref"`
	WorkflowRef string `json:"workflow_ref"`
	RunId       string `json:"run_id"`
}

type PolicyError struct {
	Type  ErrorType `json:"type"`
	Error string    `json:"error,omitempty"`
}

type RepositoryPolicy struct {
	Self  string        `json:"self"`
	Allow []AllowPolicy `json:"allow"`
}

type AllowPolicy struct {
	Repository  string            `json:"repository"`
	Ref         *string           `json:"ref,omitempty"`
	WorkflowRef *string           `json:"workflow_ref,omitempty"`
	Permissions map[string]string `json:"permissions"`
}

type ErrorType string

const (
	InternalError                           ErrorType = "internal_error"
	InvalidIDToken                          ErrorType = "invalid_id_token"
	InvalidRequest                          ErrorType = "invalid_request"
	PermissionizerNotInstalled              ErrorType = "permissionizer_not_installed"
	PermissionizerNoSufficientPermissions   ErrorType = "permissionizer_no_sufficient_permissions"
	TargetRepositoryMisconfigured           ErrorType = "target_repository_misconfigured"
	TargetRepositoryDoesNotAllowAccess      ErrorType = "target_repository_does_not_allow_access"
	TargetRepositoryDoesNotAllowRef         ErrorType = "target_repository_does_not_allow_access_from_ref"
	TargetRepositoryDoesNotAllowWorkflowRef ErrorType = "target_repository_does_not_allow_access_from_workflow_ref"
	TargetRepositoryDoesNotAllowPermission  ErrorType = "target_repository_does_not_allow_requested_permission_access"
)

type PermissionsDecision struct {
	Allow               bool
	PermissionDecisions []PermissionDecision
}

type PermissionDecision struct {
	Allow           bool
	Permission      string
	AllowedAccess   string
	RequestedAccess string
}

type ProblemDetail struct {

	// Type is a URI reference [RFC3986] that identifies the problem type.
	// This specification encourages that, when dereferenced, it provides human-readable documentation for the problem
	// type (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be
	// "about:blank".
	//
	// ref: https://tools.ietf.org/html/rfc7807#section-3.1
	Type string `json:"type"`

	// Title A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of
	// the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231],
	// Section 3.4).
	//
	// ref: https://tools.ietf.org/html/rfc7807#section-3.1
	Title string `json:"title"`

	// Status The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the
	// problem.
	//
	// ref: https://tools.ietf.org/html/rfc7807#section-3.1
	Status int `json:"status"`

	// Detail (optional) is a human-readable explanation specific to this occurrence of the problem.
	//
	// ref: https://tools.ietf.org/html/rfc7807#section-3.1
	Detail string `json:"detail,omitempty"`

	// Instance (optional) is a URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	//
	// ref: https://tools.ietf.org/html/rfc7807#section-3.1
	Instance string `json:"instance,omitempty"`
}
