# This is a sample configuration file for the permissionizer-server.
# Configure the server by modifying the values below.

# permissionizer:
#   app-link: https://github.com/apps/permissionizer
#   expected-audience: permissionizer-server (https://permissionizer.app)
#   client-id: github-app-client-id
#   private-key: |
#     -----BEGIN RSA PRIVATE KEY-----
#     ENTER YOUR GITHUB PRIVATE KEY HERE
#     -----END RSA PRIVATE KEY-----
#   webhook-secret: github-webhook-secret
#   rate-limit:
#     tokens-per-minute: 10
#     overrides:
#       permissionizer: 60
#       permissionizer/request-token: 100
#   unsecure:
#     skip-token-validation: false
