name: Tag & Release Workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    if: ${{ github.repository == 'permissionizer/server' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/reusable-docker-build.yaml
    with:
      push: true

  deploy:
    if: ${{ github.repository == 'permissionizer/server' }}
    needs: docker
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-deploy-cloud-run.yaml
    secrets: inherit
    with:
      image: ${{ needs.docker.outputs.tags }}

