name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      image:
        description: Image tag to deploy
        required: true
        type: string
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: permissionizer.app
    concurrency: permissionizer.app
    steps:
      - uses: actions/checkout@v5

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCLOUD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}

      - uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: permissionizer-server
          region: europe-west4
          image: europe-west4-docker.pkg.dev/permissionizer/ghcr/${{ inputs.image }}
